#include "SDT.h"
#include "Button.h"
#include "Display.h"
#include "Encoders.h"
#include "InfoBox.h"
#include "Menu.h"
#include "Tune.h"
#include "Utility.h"

//-------------------------------------------------------------------------------------------------------------
// Data
//-------------------------------------------------------------------------------------------------------------

int32_t IFFreq = SampleRate / 4;  // IF (intermediate) frequency
long TxRxFreq;

bool splitVFO = false;


//-------------------------------------------------------------------------------------------------------------
// Forwards
//-------------------------------------------------------------------------------------------------------------

//-------------------------------------------------------------------------------------------------------------
// Code
//-------------------------------------------------------------------------------------------------------------

/*****
  Purpose: A special variant of SetFreq() used only for calibration.

  Parameter list:
    void

  Return value;
    void

  CAUTION: SI5351_FREQ_MULT is set in the si5253.h header file and is 100UL
*****/
void SetFreqCal(void) {
  unsigned long long Clk1SetFreq, Clk2SetFreq;

  // NEVER USE AUDIONOINTERRUPTS HERE: that introduces annoying clicking noise with every frequency change
  // SI5351_FREQ_MULT is 100ULL, MASTER_CLK_MULT is 4;

  // The SSB LO frequency is always the same as the displayed transmit frequency.
  // The CW LOT frequency must be shifted by 750 Hz due to the way the CW carrier is generated by a quadrature tone.
  Clk1SetFreq = (TxRxFreq * SI5351_FREQ_MULT) * MASTER_CLK_MULT;

  if (bands[currentBand].mode == DEMOD_LSB) {
    Clk1SetFreq = (((TxRxFreq + CWFreqShift + calFreqShift) * SI5351_FREQ_MULT)) * MASTER_CLK_MULT;  // flip CWFreqShift, sign originally minus
  } else if (bands[currentBand].mode == DEMOD_USB) {
    Clk1SetFreq = (((TxRxFreq - CWFreqShift - calFreqShift) * SI5351_FREQ_MULT)) * MASTER_CLK_MULT;  // flip CWFreqShift, sign originally plus
  }

  //  The receive LO frequency is not dependent on mode or sideband.  CW frequency shift is done in DSP code.
  Clk2SetFreq = ((centerFreq * SI5351_FREQ_MULT) + IFFreq * SI5351_FREQ_MULT) * MASTER_CLK_MULT;

  //  Set and enable both RX and TX local oscillator outputs.
  si5351.set_freq(Clk2SetFreq, SI5351_CLK2);
  si5351.set_freq(Clk1SetFreq, SI5351_CLK1);
  si5351.output_enable(SI5351_CLK2, 1);
  si5351.output_enable(SI5351_CLK1, 1);

}

/*****
  Purpose: Set center tuning frequency
           NCOFreq is unchanged

  Parameter list:
    void

  Return value;
    void
*****/
void SetTxRxFreq(long freq) {
  TxRxFreq = freq;

  SetFreq();

  switch(displayScreen) {
    case DISPLAY_T41:
      ShowFrequency();          // update frequency display
      ShowOperatingStats();     // update center frequency in band info
      ShowSpectrumFreqValues(); // update spectrum frequency values
      break;

    case DISPLAY_BEACON_MONITOR:
      break;

    default:
    // no screen updates at all
    break;
  }
}

/*****
  Purpose: Reset tuning to center
           NCOFreq is set to zero

  Parameter list:
  void

  Return value;
  void
*****/
void ResetTuning() {
  centerFreq += NCOFreq;
  NCOFreq = 0L;

  SetTxRxFreq(centerFreq);

  DrawBandwidthBar();
}

/*****
  Purpose: Adjust center tuning frequency
           NCOFreq is unchanged

  Parameter list:
    long tuneChange - amound to change center freq

  Return value;
    void
*****/
void SetCenterTune(long tuneChange) {
  centerFreq += tuneChange;  // tune the master vfo

  SetTxRxFreq(centerFreq + NCOFreq);
}

/*****
  Purpose: Set NCO frequency

  Parameter list:
    void

  Return value;
    void
*****/
void SetNCOFreq(long newNCOFreq) {
  NCOFreq = newNCOFreq;
  fineTuneFlag = true;
  if (activeVFO == VFO_A) {
    currentFreqA = centerFreq + NCOFreq;
  } else {
    currentFreqB = centerFreq + NCOFreq;
  }
  // ===============  Recentering at band edges ==========
  if (spectrumZoom != 0) {
    if((NCOFreq + bands[currentBand].FHiCut) >= (96000 / (1 << spectrumZoom))) {
      NCOFreq += bands[currentBand].FHiCut;
      fineTuneFlag = false;
      resetTuningFlag = true;
      return;
    }
    if((NCOFreq + bands[currentBand].FLoCut) <= (-96000 / (1 << spectrumZoom))) {
      NCOFreq += bands[currentBand].FLoCut;
      fineTuneFlag = false;
      resetTuningFlag = true;
      return;
    }
  } else {
    if (NCOFreq > 142000 || NCOFreq < -43000) {  // Offset tuning window in zoom 1x
      fineTuneFlag = false;
      resetTuningFlag = true;
      return;
    }
  }

  TxRxFreq = centerFreq + NCOFreq;
}

/*****
  Purpose: Set fine tuning frequency

  Parameter list:
    void

  Return value;
    void
*****/
void SetFineTune(long tuneChange) {
  SetNCOFreq(NCOFreq + tuneChange);
}

/*****
  Purpose: Set si5351 frequency

  Parameter list:
    void

  Return value;
    void

  CAUTION: SI5351_FREQ_MULT is set in the si5253.h header file and is 100UL
*****/
void SetFreq() {
  unsigned long long Clk1SetFreq, Clk2SetFreq;

  // NEVER USE AUDIONOINTERRUPTS HERE: that introduces annoying clicking noise with every frequency change
  // SI5351_FREQ_MULT is 100ULL, MASTER_CLK_MULT is 4;

  // The SSB LO frequency is always the same as the displayed transmit frequency.
  // The CW LOT frequency must be shifted by 750 Hz due to the way the CW carrier is generated by a quadrature tone.
  Clk1SetFreq = (TxRxFreq * SI5351_FREQ_MULT) * MASTER_CLK_MULT;

  if (radioState == CW_TRANSMIT_STRAIGHT_STATE || radioState == CW_TRANSMIT_KEYER_STATE) {
    if (bands[currentBand].mode == DEMOD_LSB) {
      Clk1SetFreq = (((TxRxFreq + CWFreqShift + calFreqShift) * SI5351_FREQ_MULT)) * MASTER_CLK_MULT;  // flip CWFreqShift, sign originally minus
    } else {
      if (bands[currentBand].mode == DEMOD_USB) {
        Clk1SetFreq = (((TxRxFreq - CWFreqShift - calFreqShift) * SI5351_FREQ_MULT)) * MASTER_CLK_MULT;  //  flip CWFreqShift, sign originally plus
      }
    }
  }

  //  The receive LO frequency is not dependent on mode or sideband.  CW frequency shift is done in DSP code.
  Clk2SetFreq = ((centerFreq * SI5351_FREQ_MULT) + IFFreq * SI5351_FREQ_MULT) * MASTER_CLK_MULT;

  if (radioState == SSB_RECEIVE_STATE || radioState == CW_RECEIVE_STATE) {   //  Receive state
    si5351.set_freq(Clk2SetFreq, SI5351_CLK2);
    si5351.output_enable(SI5351_CLK1, 0);  // CLK1 (transmit) off during receive to prevent birdies
    si5351.output_enable(SI5351_CLK2, 1);
  }

  if (radioState == SSB_TRANSMIT_STATE || radioState == CW_TRANSMIT_STRAIGHT_STATE || radioState == CW_TRANSMIT_KEYER_STATE) {  // Transmit state
    si5351.set_freq(Clk1SetFreq, SI5351_CLK1);
    si5351.output_enable(SI5351_CLK2, 0);  // CLK2 (receive) off during transmit to prevent spurious outputs
    si5351.output_enable(SI5351_CLK1, 1);
  }
}

FLASHMEM void SplitVFOFollowup() {
  // *** TODO: need to reestablish "Split Active" that didn't work in ver49.2k ***
  tft.setTextColor(RA8875_RED);
  tft.setCursor(FILTER_PARAMETERS_X + 180, FILTER_PARAMETERS_Y + 6);
  tft.print("Split Active");
  splitVFO = true;
}

/*****
  Purpose: Set VFO A to receive frequency and VFO B to the transmit frequency

  Parameter list:
    void

  Return value;
    void
*****/
FLASHMEM void DoSplitVFO() {
  currentFreqB = currentFreqA;

  // GetMenuValue(minValue, maxValue, startValue, increment, prompt, valueOffset)
  GetMenuValue(-40, 30, &currentFreqB, SPLIT_INCREMENT, "Xmit offset:", 200, NULL, NULL, &SplitVFOFollowup);
}
