
#include <si5351.h>                    // https://github.com/etherkit/Si5351Arduino

#include "SDT.h"

#include "Button.h"
#include "Display.h"
#include "Encoders.h"
#include "Filter.h"
#include "InfoBox.h"
#include "Menu.h"
#include "Tune.h"
#include "Utility.h"

//-------------------------------------------------------------------------------------------------------------
// Data
//-------------------------------------------------------------------------------------------------------------

int TxRxFreq, NCOFreq;

bool splitVFO;

int CWFreqShift = 750;
int calFreqShift = 0;

Si5351 si5351;

//-------------------------------------------------------------------------------------------------------------
// Code
//-------------------------------------------------------------------------------------------------------------

FLASHMEM void InitSI5351() {
  si5351.reset();
  si5351.init(SI5351_CRYSTAL_LOAD_10PF, Si_5351_crystal, freqCorrectionFactor);
  si5351.set_ms_source(SI5351_CLK2, SI5351_PLLB); //  Allows CLK1 and CLK2 to exceed 100 MHz simultaneously.
  si5351.drive_strength(SI5351_CLK1, SI5351_DRIVE_8MA);
  si5351.drive_strength(SI5351_CLK2, SI5351_DRIVE_8MA);
}

void SetSI5351FreqCorFactor(int factor) {
  si5351.init(SI5351_CRYSTAL_LOAD_10PF, Si_5351_crystal, factor);
}

/*****
  Purpose: A special variant of SetFreq() used only for calibration.

  CAUTION: SI5351_FREQ_MULT is set in the si5253.h header file and is 100UL
*****/
FLASHMEM void SetFreqCal(long calFreqShift) {
  unsigned long long Clk1SetFreq, Clk2SetFreq;

  // NEVER USE AUDIONOINTERRUPTS HERE: that introduces annoying clicking noise with every frequency change
  // SI5351_FREQ_MULT is 100ULL, MASTER_CLK_MULT is 4;

  // The SSB LO frequency is always the same as the displayed transmit frequency.
  // The CW LOT frequency must be shifted by 750 Hz due to the way the CW carrier is generated by a quadrature tone.
  Clk1SetFreq = (TxRxFreq * SI5351_FREQ_MULT) * MASTER_CLK_MULT;

  if(bands[currentBand].demod == DEMOD_LSB) {
    Clk1SetFreq = (((TxRxFreq + CWFreqShift + calFreqShift) * SI5351_FREQ_MULT)) * MASTER_CLK_MULT;  // flip CWFreqShift, sign originally minus
  } else if(bands[currentBand].demod == DEMOD_USB) {
    Clk1SetFreq = (((TxRxFreq - CWFreqShift - calFreqShift) * SI5351_FREQ_MULT)) * MASTER_CLK_MULT;  // flip CWFreqShift, sign originally plus
  }

  //  The receive LO frequency is not dependent on mode or sideband.  CW frequency shift is done in DSP code.
  Clk2SetFreq = ((centerFreq * SI5351_FREQ_MULT) + 48000.0 * SI5351_FREQ_MULT) * MASTER_CLK_MULT;

  //  Set and enable both RX and TX local oscillator outputs.
  si5351.set_freq(Clk2SetFreq, SI5351_CLK2);
  si5351.set_freq(Clk1SetFreq, SI5351_CLK1);
  si5351.output_enable(SI5351_CLK2, 1);
  si5351.output_enable(SI5351_CLK1, 1);

}

/*****
  Purpose: Set center tuning frequency
           NCOFreq is unchanged
*****/
void SetTxRxFreq(int freq) {
  TxRxFreq = freq;

  SetFreq();

  switch(displayState) {
    case DISPLAY_T41:
      ShowFrequency();          // update frequency display
      ShowOperatingStats();     // update center frequency in band info
      ShowSpectrumFreqValues(); // update spectrum frequency values
      break;

    case DISPLAY_BEACON_MONITOR:
      break;

    case DISPLAY_FULL_MENU:
      ShowFrequency();
      ShowOperatingStats();
      break;

    default:
    // no screen updates at all
    break;
  }
}

/*****
  Purpose: Reset tuning to center
           NCOFreq is set to zero

  Parameter list:
  void

  Return value:
  void
*****/
void ResetTuning() {
  centerFreq += NCOFreq;
  NCOFreq = 0L;

  SetTxRxFreq(centerFreq);

  DrawBandwidthBar();
}

/*****
  Purpose: Adjust center tuning frequency
           NCOFreq is unchanged

  Parameter list:
    long tuneChange - amound to change center freq
*****/
void SetCenterTune(int tuneChange) {
  centerFreq += tuneChange;  // tune the master vfo

  SetTxRxFreq(centerFreq + NCOFreq);
}

/*****
  Purpose: Set NCO frequency
*****/
void SetNCOFreq(int newNCOFreq) {
  int lowSideAdj = 0, highSideAdj = 0;

  switch(bands[currentBand].demod) {
    case DEMOD_USB:
    case DEMOD_PSK31_WAV:
    case DEMOD_PSK31:
    case DEMOD_FT8:
    case DEMOD_FT8_WAV:
      lowSideAdj = 0;
      highSideAdj = currentFilterHiCut;
      break;

    case DEMOD_LSB:
      lowSideAdj = currentFilterHiCut;
      highSideAdj = 0;
      break;

    case DEMOD_AM:
    case DEMOD_SAM:
      break;

    case DEMOD_NFM:
      break;
  }

  NCOFreq = newNCOFreq;
  fineTuneFlag = true;
  if(activeVFO == VFO_A) {
    currentFreqA = centerFreq + NCOFreq;
  } else {
    currentFreqB = centerFreq + NCOFreq;
  }

  // recenter at band edges
  if(spectrumZoom != 0) {
    if((NCOFreq + highSideAdj) >= (96000 / (1 << spectrumZoom))) {
      NCOFreq += highSideAdj;
      fineTuneFlag = false;
      resetTuningFlag = true;
      return;
    }
    if((NCOFreq - lowSideAdj) <= (-96000 / (1 << spectrumZoom))) {
      NCOFreq -= lowSideAdj;
      fineTuneFlag = false;
      resetTuningFlag = true;
      return;
    }
  } else if(NCOFreq > 142000 || NCOFreq < -43000) {  // Offset tuning window in zoom 1x
    fineTuneFlag = false;
    resetTuningFlag = true;
    return;
  }

  TxRxFreq = centerFreq + NCOFreq;
}

/*****
  Purpose: Set fine tuning frequency
*****/
void SetFineTune(int tuneChange) {
  SetNCOFreq(NCOFreq + tuneChange);
}

/*****
  Purpose: Set si5351 frequency

  CAUTION: SI5351_FREQ_MULT is set in the si5253.h header file and is 100UL
*****/
void SetFreq() {
  unsigned long long Clk1SetFreq, Clk2SetFreq;

  // NEVER USE AUDIONOINTERRUPTS HERE: that introduces annoying clicking noise with every frequency change
  // SI5351_FREQ_MULT is 100ULL, MASTER_CLK_MULT is 4;

  // The SSB LO frequency is always the same as the displayed transmit frequency.
  // The CW LOT frequency must be shifted by 750 Hz due to the way the CW carrier is generated by a quadrature tone.
  Clk1SetFreq = (TxRxFreq * SI5351_FREQ_MULT) * MASTER_CLK_MULT;

  if(radioState == CW_TRANSMIT_STRAIGHT_STATE || radioState == CW_TRANSMIT_KEYER_STATE) {
    if(bands[currentBand].demod == DEMOD_LSB) {
      Clk1SetFreq = (((TxRxFreq + CWFreqShift) * SI5351_FREQ_MULT)) * MASTER_CLK_MULT;  // flip CWFreqShift, sign originally minus
    } else {
      if(bands[currentBand].demod == DEMOD_USB) {
        Clk1SetFreq = (((TxRxFreq - CWFreqShift) * SI5351_FREQ_MULT)) * MASTER_CLK_MULT;  //  flip CWFreqShift, sign originally plus
      }
    }
  }

  //  The receive LO frequency is not dependent on mode or sideband.  CW frequency shift is done in DSP code.
  Clk2SetFreq = ((centerFreq * SI5351_FREQ_MULT) + 48000.0 * SI5351_FREQ_MULT) * MASTER_CLK_MULT;

  if(radioState == SSB_RECEIVE_STATE || radioState == CW_RECEIVE_STATE) {   //  Receive state
    si5351.set_freq(Clk2SetFreq, SI5351_CLK2);
    si5351.output_enable(SI5351_CLK1, 0);  // CLK1 (transmit) off during receive to prevent birdies
    si5351.output_enable(SI5351_CLK2, 1);
  }

  if(radioState == SSB_TRANSMIT_STATE || radioState == CW_TRANSMIT_STRAIGHT_STATE || radioState == CW_TRANSMIT_KEYER_STATE) {  // Transmit state
    si5351.set_freq(Clk1SetFreq, SI5351_CLK1);
    si5351.output_enable(SI5351_CLK2, 0);  // CLK2 (receive) off during transmit to prevent spurious outputs
    si5351.output_enable(SI5351_CLK1, 1);
  }
}

FLASHMEM void SplitVFOFollowup() {
  // *** TODO: need to reestablish "Split Active" that didn't work in ver49.2k ***
  tft.setTextColor(RA8875_RED);
  tft.setCursor(FILTER_PARAMETERS_X + 180, FILTER_PARAMETERS_Y + 6);
  tft.print("Split Active");
  splitVFO = true;
}

/*****
  Purpose: Set VFO A to receive frequency and VFO B to the transmit frequency
*****/
FLASHMEM void DoSplitVFO() {
  currentFreqB = currentFreqA;

  // GetMenuValue(minValue, maxValue, startValue, increment, prompt, valueOffset)
  GetMenuValue(-40, 30, &currentFreqB, SPLIT_INCREMENT, "Xmit offset:", 200, NULL, NULL, &SplitVFOFollowup);
}
